version: '3'

services:
  api_exercise:
    build: ./Exercise-2
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://Exercise-2:5432/jpa_test?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: postgres
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      Exercise-2:
          condition: service_healthy
  Exercise-2:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jpa_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5